# Generated by Django 5.2.1 on 2025-05-10 02:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sunlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0, help_text='Sunlight status value')),
                ('r', models.FloatField(default=0.2, help_text='Red component of sunlight')),
                ('g', models.FloatField(default=0.2, help_text='Green component of sunlight')),
                ('b', models.FloatField(default=0.2, help_text='Blue component of sunlight')),
                ('brightness', models.FloatField(default=0.8, help_text='Brightness of sunlight')),
            ],
        ),
    ]
