# Generated by Django 5.2.1 on 2025-05-10 02:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('speed', models.FloatField(default=0.2, help_text='Wind speed value in m/s')),
                ('status', models.IntegerField(choices=[(0, 'Off'), (1, 'On')], default=0, help_text='Wind status value')),
            ],
        ),
    ]
